name: tk8base

x-vols: &app_vols
  volumes:
    # production:
#    - data:/app/data
    # development:
    - ./:/app
    - ./docker/php.ini:/usr/local/etc/php/conf.d/99-moodle.ini

services:
  app:
    build:
      context: .
    tty: true
    restart: always
    ports:
      - "${HTTP_APP_PORT:-80}:80"
      - "${HTTPS_APP_PORT:-443}:443"
      - "${HTTPS_APP_PORT:-443}:443/udp"
    <<: *app_vols
    env_file:
      - ./.env
    environment:
      RELEASE: "dev"
      # Development
      SERVER_NAME: :80  # disable HTTPS
    networks:
      lan:
        ipv4_address: 192.168.0.225
#    networks:
#      - lan
    depends_on:
      - db
#    depends_on:
#      deploy:
#        condition: service_completed_successfully

  db:
    image: mariadb:latest
    restart: unless-stopped
    tty: true
    env_file:
      - ./.env
    ports:
      - '${DB_MARIADB_PORT:-3306}:3306'
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      retries: 3
      timeout: 5s
    networks:
      lan:
        ipv4_address: 192.168.0.226
#    networks:
#      - lan

  # development only
  mailpit:
    image: axllent/mailpit
    restart: unless-stopped
    tty: true
    volumes:
      - ./docker/mailpit:/data
    ports:
      - "${HTTP_MAILPIT_PORT:-8025}:8025" # Web UI
      - "${SMTP_MAILPIT_PORT:-1025}:1025" # SMTP server
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

    networks:
      lan:
        ipv4_address: 192.168.0.227
#    networks:
#      - lan


volumes:
  app:
  db:

#networks:
#  lan:
#    driver: bridge

networks:
  lan:
    driver: ipvlan
    driver_opts:
      ipvlan_mode: l2
      parent: wlp1s0 # Replace with your host interface (e.g., enp0s3) (get from .env)
    ipam:
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1
          ip_range: 192.168.0.0/24
