name: tk8base-lan

x-vols: &app_vols
  volumes:
    # production:
#    - data:/app/data
    # development:
    - ./:/app
    - ./docker/php.ini:/usr/local/etc/php/conf.d/99-moodle.ini

services:
  app:
    build:
      context: .
    tty: true
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    <<: *app_vols
    env_file:
      - ./.env
    environment:
      RELEASE: "dev"
      # Development
      SERVER_NAME: :80  # disable HTTPS
      HOSTNAME: 192.168.0.225
    networks:
      lan:
        ipv4_address: 192.168.0.225
    depends_on:
      - db
#    depends_on:
#      deploy:
#        condition: service_completed_successfully

  db:
    image: mariadb:latest
    restart: unless-stopped
    tty: true
    env_file:
      - ./.env
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      retries: 3
      timeout: 5s
    networks:
      lan:
        ipv4_address: 192.168.0.226

volumes:
  app:
  db:

networks:
  lan:
    driver: ipvlan
    driver_opts:
      ipvlan_mode: l2
      parent: ${PARENT_NIC}
    ipam:
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1
          ip_range: 192.168.0.240/28

# Note: this seems to be working for remote machines but will not work for the host machine.
#       You need to link the ip to the host machine. Below are examples I found, but do not seem to work???
#       It would be nice to find an easier way to handle this.

# This creates a new interface ipvlan94 in the host's namespace, which acts as the gateway for the Docker network.
# $ sudo ip link add link eth0 name ipvlan94 type ipvlan mode l3
# $ sudo ip addr add 192.168.94.1/24 dev ipvlan94
# $ sudo ip link set ipvlan94 up
# Enable IP forwarding on the host (if not already enabled):
# sudo sysctl net.ipv4.ip_forward=1
# Add a route to your external router (essential for internet access):

# ip link set eth1 promisc on
